spring:
  datasource:
    url: jdbc:mysql://db.darkbright.gabia.io:3306/dbdarkbright
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: darkbright
    password: ofzhf@@726
    max-lifetime: 28000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
